version: "3"

services:
  adf_bot:
    image: adf_bot
    container_name: adfBot
    restart: always
    # build: .
    working_dir: /app/
    command:
      [
      "python3",
      "-u",
      "supervisor_check.py"
      ]
    volumes:
      - .Xauthority:/root/.Xauthority
