version: "3"

services:
  supervisorTest:
    image: supervisorTest 
    container_name: supervisortest
    restart: always
    # build: .
    working_dir: /app/
    command:
      [
      "python3",
      "-u",
      "supervisor_check.py"
      ]
    volumes:
      - .Xauthority:/root/.Xauthority
